In [15]:
import numpy as np
from fontTools.misc.bezierTools import epsilon

epsilon = 0.0000001
# 부동소수점 오차 방지 ( 0으로 나누어지는 문제 해결을 위해서
def step_func(t):
# 퍼셉트론의 활성화 함수
    if t > epsilon:
        return 1
    else:
        return 0
X = np.array([[0, 0, 1 ], [0, 1, 1],[1,0,1],[1, 1, 1]])
# 맨 끝의 1은 바이어스를 위한 입력 신호 1이다.
y = np.array([0, 1, 1, 0])
#정답을 저장하는 넌파이 행렬
W = np.zeros(len(X[0]))
def perceptron_fit(X, Y, epochs=10): # 퍼셉트론 학습 알고리즘 구현
    global W
    eta = 0.2
    # 학습률
    for t in range(epochs):
        print("epoch=", t, "======================")
        for i in range(len(X)):
            predict = step_func(np.dot(X[i], W))
            error = Y[i] - predict # 오차 계산
            W += eta * error * X[i] # 가중치 업데이트
            print("현재 처리 입력=",X[i],"정답=",Y[i],"출력=",predict,"변경된 가중치=", W)
            print("================================")

In [16]:
perceptron_fit(X, y, 20)

epoch= 0 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 0 변경된 가중치= [0. 0. 0.]
현재 처리 입력= [0 1 1] 정답= 1 출력= 0 변경된 가중치= [0.  0.2 0.2]
현재 처리 입력= [1 0 1] 정답= 1 출력= 1 변경된 가중치= [0.  0.2 0.2]
현재 처리 입력= [1 1 1] 정답= 0 출력= 1 변경된 가중치= [-0.2  0.   0. ]
epoch= 1 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 0 변경된 가중치= [-0.2  0.   0. ]
현재 처리 입력= [0 1 1] 정답= 1 출력= 0 변경된 가중치= [-0.2  0.2  0.2]
현재 처리 입력= [1 0 1] 정답= 1 출력= 0 변경된 가중치= [0.  0.2 0.4]
현재 처리 입력= [1 1 1] 정답= 0 출력= 1 변경된 가중치= [-0.2  0.   0.2]
epoch= 2 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 1 변경된 가중치= [-0.2  0.   0. ]
현재 처리 입력= [0 1 1] 정답= 1 출력= 0 변경된 가중치= [-0.2  0.2  0.2]
현재 처리 입력= [1 0 1] 정답= 1 출력= 0 변경된 가중치= [0.  0.2 0.4]
현재 처리 입력= [1 1 1] 정답= 0 출력= 1 변경된 가중치= [-0.2  0.   0.2]
epoch= 3 ======================
현재 처리 입력= [0 0 1] 정답= 0 출력= 1 변경된 가중치= [-0.2  0.   0. ]
현재 처리 입력= [0 1 1] 정답= 1 출력= 0 변경된 가중치= [-0.2  0.2  0.2]
현재 처리 입력= [1 0 1] 정답= 1 출력= 0 변경된 가중치= [0.  0.2 0.4]
현재 처리 입력= [1 1 1] 정답= 0 출력= 1 변경된 가중치= [-0.2  0.   0.

In [17]:
print(W)

[-0.2  0.   0.2]


In [18]:
def perceptron_predict(X): # 예측
    # 에측
    global W
    for x in X:
        print(x[0], x[1], "->", step_func(np.dot(x, W)))

In [19]:
perceptron_predict(X)

0 0 -> 1
0 1 -> 1
1 0 -> 0
1 1 -> 0


In [20]:
from sklearn.linear_model import Perceptron

In [21]:
# AND GATE
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 0, 0, 1]
percept = Perceptron() #클래스
percept.fit(X, y)
print(percept.predict(X))

[0 0 0 1]


In [22]:
# or GATE
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 1, 1, 1]
percept = Perceptron() #클래스
percept.fit(X, y)
print(percept.predict(X))

[0 1 1 1]


In [23]:
# XOR GATE
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [0, 1, 1, 0]
percept = Perceptron() #클래스
percept.fit(X, y)
print(percept.predict(X))

[0 0 0 0]
